# Solution status - page 504

bool RTK_or_PDP_GLIDE_solution

uint8 Unknown_or_default_Klobuchar_model = 0
uint8 Klobuchar_Broadcast = 1
uint8 SBAS_Broadcast = 2
uint8 Multi_frequency_Computed = 3
uint8 PSRDiff_correction = 4
uint8 Novatel_Blended_Iono_Value = 5
uint8 pseudorange_iono_correction

bool RTK_assist_active
bool antenna_information_status
bool reserved
bool used_terrain_compensation_corrections