#INSPVAX header

string port
int32 sequence

float32 idle_time

uint8 UNKNOWN = 20
uint8 APPROXIMATE = 20
uint8 COARSEADJUSTING = 20
uint8 COARSE = 20
uint8 COARSESTEERING = 20
uint8 FREEWHEELING = 20
uint8 FINEADJUSTING = 20
uint8 FINE = 20
uint8 FINEBACKUPSTEERING = 20
uint8 FINESTEERING = 20
uint8 SATTIME = 20
uint8 time_status

uint32 week
float64 seconds

uint32 receiver_status
uint32 reserved
uint32 receiver_sw_version