# Define how to read serial
nmea_serial_driver_node:
  port: /dev/ttyUSB0
  baud: 115200
  NMEA_pub_topic: /nmea/sentence

nmea_parser_node:
  GPFPD: true
  GTIMU: false
  GPGGA: false
  NVSTD: false
  GPCHC: true

# used for NavsatFix & Imu message, if use_gnss_time is true.
time_set:
  time_zone: 8  # parse gnss time to ROS NavsatFix stamp, if use GPGGA defalut time zone is 0
  leap_second: 27 #  used for GPFPD: leap second from 1970s to 2022 is 27

NavsatFix_generator_node:
  NavsatFix_generate_from: GPCHC  # optional: GPCHC, GPFPD, GPGGA
  use_gnss_time: true


Imu_generator_node:
  Imu_generate_from: GPCHC  # optional: GPCHC, GPFPD-GTIMU
  use_gnss_time: true