# Define how to read serial
Nmea_serial_reader_node:
  port: /dev/ttyUSB0
  baud: 115200
  timeout: 1000

Binary_serial_reader_node:
  INSPVAXB: true
  GPFPS: true
  GPFPS_BIN: false
  GTIMU: true
  GTIMU_BIN: false
  GPGGA: true
  GPFPD: true
  GPCHC: true

Nmea_parser_node:
  GPFPD: true
  GTIMU: true
  GPGGA: true
  NVSTD: false
  GPCHC: true

Spanlog_parser_node:
  INSPVAXA: false

# Used for TimeReference message, and NavsatFix & Imu message if "use_gnss_time" is true.
time_set:
  time_zone: 8  # parse gnss time to ROS NavsatFix stamp, if use GPGGA defalut time zone is 0
  leap_second: 27 #  used for GPFPD: leap second from 1970s to 2022 is 27

NavsatFix_generator_node:
  NavsatFix_generate_from: GPCHC  # optional: GPCHC, GPFPD, GPGGA, INSPVAXB
  frame_id: gnss_link
  use_gnss_time: true # NavsatFix message header stamp is gnss time


Imu_generator_node:
  Imu_generate_from: GPCHC  # optional: GPCHC, GPFPD-GTIMU, INSPVAXB-GTIMU, NVSTD-GPFPD-GTIMU
  frame_id: imu_link
  use_gnss_time: true # IMU message header stamp is gnss time

# In case of gnss point refer to imu original point. No external matrix.
Odometry_generator_node:
  coordinate_type: UTM # optional: ENU(first point refer to zero), UTM, LLA
  show_altitude: true
  parent_frame_id: map
  child_frame_id: imu_link
  publish_tf: false