# Define how to read serial
Nmea_serial_driver_node:
  port: /dev/ttyUSB0
  baud: 115200
  timeout: 1000

Binary_serial_driver_node:
  INSPVAXB: true
  GPFPS: false
  GPFPS_BIN: false
  GTIMU: false
  GTIMU_BIN: false
  GPGGA: true
  GPFPD: true

Nmea_parser_node:
  GPFPD: false
  GTIMU: true
  GPGGA: false
  NVSTD: false
  GPCHC: false

Spanlog_parser_node:
  INSPVAXA: false

# Used for TimeReference message, and NavsatFix & Imu message if "use_gnss_time" is true.
time_set:
  time_zone: 8  # parse gnss time to ROS NavsatFix stamp, if use GPGGA defalut time zone is 0
  leap_second: 27 #  used for GPFPD: leap second from 1970s to 2022 is 27

NavsatFix_generator_node:
  NavsatFix_generate_from: INSPVAXB  # optional: GPCHC, GPFPD, GPGGA, INSPVAXB
  frame_id: base_link # for rviz GNSS map visualization, we should use "base_link".
  use_gnss_time: true # NavsatFix message header stamp is gnss time


Imu_generator_node:
  Imu_generate_from: INSPVAXB-GTIMU  # optional: GPCHC, GPFPD-GTIMU, INSPVAXB-GTIMU, NVSTD-GPFPD-GTIMU
  frame_id: base_link
  use_gnss_time: true # IMU message header stamp is gnss time

# In case of gnss point refer to imu original point. No external matrix.
Odometry_generator_node:
  coordinate_type: ENU # optional: ENU(first point refer to zero), UTM, LLA
  show_altitude: true
  parent_frame_id: odom
  child_frame_id: navsat_link