// Generated by gencpp from file integrated_navigation_reader/ASCIIHeader.msg
// DO NOT EDIT!


#ifndef INTEGRATED_NAVIGATION_READER_MESSAGE_ASCIIHEADER_H
#define INTEGRATED_NAVIGATION_READER_MESSAGE_ASCIIHEADER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <integrated_navigation_reader/Log_ReceiverStatus.h>

namespace integrated_navigation_reader
{
template <class ContainerAllocator>
struct ASCIIHeader_
{
  typedef ASCIIHeader_<ContainerAllocator> Type;

  ASCIIHeader_()
    : port()
    , sequence(0)
    , idle_time(0.0)
    , time_status(0)
    , week(0)
    , seconds(0.0)
    , receiver_status()
    , reserved(0)
    , receiver_sw_version(0)  {
    }
  ASCIIHeader_(const ContainerAllocator& _alloc)
    : port(_alloc)
    , sequence(0)
    , idle_time(0.0)
    , time_status(0)
    , week(0)
    , seconds(0.0)
    , receiver_status(_alloc)
    , reserved(0)
    , receiver_sw_version(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _port_type;
  _port_type port;

   typedef int32_t _sequence_type;
  _sequence_type sequence;

   typedef float _idle_time_type;
  _idle_time_type idle_time;

   typedef uint8_t _time_status_type;
  _time_status_type time_status;

   typedef uint32_t _week_type;
  _week_type week;

   typedef double _seconds_type;
  _seconds_type seconds;

   typedef  ::integrated_navigation_reader::Log_ReceiverStatus_<ContainerAllocator>  _receiver_status_type;
  _receiver_status_type receiver_status;

   typedef uint32_t _reserved_type;
  _reserved_type reserved;

   typedef uint32_t _receiver_sw_version_type;
  _receiver_sw_version_type receiver_sw_version;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(UNKNOWN)
  #undef UNKNOWN
#endif
#if defined(_WIN32) && defined(APPROXIMATE)
  #undef APPROXIMATE
#endif
#if defined(_WIN32) && defined(COARSEADJUSTING)
  #undef COARSEADJUSTING
#endif
#if defined(_WIN32) && defined(COARSE)
  #undef COARSE
#endif
#if defined(_WIN32) && defined(COARSESTEERING)
  #undef COARSESTEERING
#endif
#if defined(_WIN32) && defined(FREEWHEELING)
  #undef FREEWHEELING
#endif
#if defined(_WIN32) && defined(FINEADJUSTING)
  #undef FINEADJUSTING
#endif
#if defined(_WIN32) && defined(FINE)
  #undef FINE
#endif
#if defined(_WIN32) && defined(FINEBACKUPSTEERING)
  #undef FINEBACKUPSTEERING
#endif
#if defined(_WIN32) && defined(FINESTEERING)
  #undef FINESTEERING
#endif
#if defined(_WIN32) && defined(SATTIME)
  #undef SATTIME
#endif

  enum {
    UNKNOWN = 20u,
    APPROXIMATE = 60u,
    COARSEADJUSTING = 80u,
    COARSE = 100u,
    COARSESTEERING = 120u,
    FREEWHEELING = 130u,
    FINEADJUSTING = 140u,
    FINE = 160u,
    FINEBACKUPSTEERING = 170u,
    FINESTEERING = 180u,
    SATTIME = 200u,
  };


  typedef boost::shared_ptr< ::integrated_navigation_reader::ASCIIHeader_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::integrated_navigation_reader::ASCIIHeader_<ContainerAllocator> const> ConstPtr;

}; // struct ASCIIHeader_

typedef ::integrated_navigation_reader::ASCIIHeader_<std::allocator<void> > ASCIIHeader;

typedef boost::shared_ptr< ::integrated_navigation_reader::ASCIIHeader > ASCIIHeaderPtr;
typedef boost::shared_ptr< ::integrated_navigation_reader::ASCIIHeader const> ASCIIHeaderConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::integrated_navigation_reader::ASCIIHeader_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::integrated_navigation_reader::ASCIIHeader_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::integrated_navigation_reader::ASCIIHeader_<ContainerAllocator1> & lhs, const ::integrated_navigation_reader::ASCIIHeader_<ContainerAllocator2> & rhs)
{
  return lhs.port == rhs.port &&
    lhs.sequence == rhs.sequence &&
    lhs.idle_time == rhs.idle_time &&
    lhs.time_status == rhs.time_status &&
    lhs.week == rhs.week &&
    lhs.seconds == rhs.seconds &&
    lhs.receiver_status == rhs.receiver_status &&
    lhs.reserved == rhs.reserved &&
    lhs.receiver_sw_version == rhs.receiver_sw_version;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::integrated_navigation_reader::ASCIIHeader_<ContainerAllocator1> & lhs, const ::integrated_navigation_reader::ASCIIHeader_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace integrated_navigation_reader

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::integrated_navigation_reader::ASCIIHeader_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::integrated_navigation_reader::ASCIIHeader_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::integrated_navigation_reader::ASCIIHeader_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::integrated_navigation_reader::ASCIIHeader_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::integrated_navigation_reader::ASCIIHeader_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::integrated_navigation_reader::ASCIIHeader_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::integrated_navigation_reader::ASCIIHeader_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7bd354159f81ccee0225357433aedd3e";
  }

  static const char* value(const ::integrated_navigation_reader::ASCIIHeader_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7bd354159f81cceeULL;
  static const uint64_t static_value2 = 0x0225357433aedd3eULL;
};

template<class ContainerAllocator>
struct DataType< ::integrated_navigation_reader::ASCIIHeader_<ContainerAllocator> >
{
  static const char* value()
  {
    return "integrated_navigation_reader/ASCIIHeader";
  }

  static const char* value(const ::integrated_navigation_reader::ASCIIHeader_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::integrated_navigation_reader::ASCIIHeader_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#INSPVAX header\n"
"\n"
"string port\n"
"int32 sequence\n"
"\n"
"float32 idle_time\n"
"\n"
"uint8 UNKNOWN = 20\n"
"uint8 APPROXIMATE = 60\n"
"uint8 COARSEADJUSTING = 80\n"
"uint8 COARSE = 100\n"
"uint8 COARSESTEERING = 120\n"
"uint8 FREEWHEELING = 130\n"
"uint8 FINEADJUSTING = 140\n"
"uint8 FINE = 160\n"
"uint8 FINEBACKUPSTEERING = 170\n"
"uint8 FINESTEERING = 180\n"
"uint8 SATTIME = 200\n"
"uint8 time_status\n"
"\n"
"uint32 week\n"
"float64 seconds\n"
"\n"
"Log_ReceiverStatus receiver_status\n"
"uint32 reserved\n"
"uint32 receiver_sw_version\n"
"================================================================================\n"
"MSG: integrated_navigation_reader/Log_ReceiverStatus\n"
"# Receiver status - page 858\n"
"\n"
"bool OK = 0\n"
"bool Valid = 0\n"
"bool No_error = 0\n"
"bool No_overrun = 0\n"
"\n"
"bool Warning = 1\n"
"bool Error = 1\n"
"bool Failure = 1\n"
"bool Overrun = 1\n"
"bool Invalid = 1\n"
"\n"
"# N0\n"
"bool error_flag\n"
"\n"
"bool Within_specifications = 0\n"
"bool temperature_status\n"
"bool voltage_supply_status\n"
"\n"
"bool Powered = 0\n"
"bool Not_powered = 1\n"
"bool primary_antenna_power_status\n"
"\n"
"# N1\n"
"bool LNA_failure\n"
"\n"
"bool Open_and_Antenna_disconnected = 1\n"
"bool primary_antenna_open_circuit_flag\n"
"\n"
"bool Short_circuit_detected = 1\n"
"bool primary_antenna_short_circuit_flag\n"
"\n"
"bool No_overload = 0\n"
"bool Overload = 1\n"
"bool CPU_overload_flag\n"
"\n"
"# N2\n"
"bool COM_port_transmit_buffer_overrun\n"
"\n"
"bool Not_detected = 0\n"
"bool Detected = 1\n"
"bool spoofing_detection_status\n"
"\n"
"bool reserved\n"
"bool link_overrun_flag\n"
"\n"
"# N3\n"
"bool input_overrun_flag\n"
"bool aux_transmit_overrun_flag\n"
"\n"
"bool Out_of_range = 1\n"
"bool antenna_gain_state\n"
"\n"
"bool Jammer_Detected = 1\n"
"bool jammer_detected\n"
"\n"
"# N4\n"
"bool No_INS_reset = 0\n"
"bool INS_reset = 1\n"
"bool INS_reset_flag\n"
"\n"
"bool No_IMU_communication = 1\n"
"bool IMU_communication_failure\n"
"\n"
"bool GPS_almanac_flag_UTC_known\n"
"bool position_solution_flag\n"
"\n"
"# N5\n"
"bool Not_fixed = 0\n"
"bool Fixed = 1\n"
"bool position_fixed_flag\n"
"\n"
"bool Enabled_clock_steering = 0\n"
"bool Disabled_clock_steering = 1\n"
"bool clock_steering_status\n"
"\n"
"bool clock_model_flag\n"
"\n"
"bool UnLocked = 0\n"
"bool Locked = 1\n"
"bool external_oscillator_locked_flag\n"
"\n"
"# N6\n"
"bool software_resource\n"
"\n"
"bool OEM6_or_earlier_format = 0\n"
"bool OEM7_format = 1\n"
"bool status_error_version_bit\n"
"\n"
"bool version_bit_1\n"
"\n"
"bool Normal_tracking = 0\n"
"bool HDR_tracking = 1\n"
"bool tracking_mode\n"
"\n"
"# N7\n"
"bool Disables_digital_filtering = 0\n"
"bool Enables_digital_filtering = 1\n"
"bool digital_filtering_enabled\n"
"\n"
"bool No_event = 0\n"
"bool Event = 1\n"
"bool auxiliary_3_status_event_flag\n"
"bool auxiliary_2_status_event_flag\n"
"bool auxiliary_1_status_event_flag\n"
;
  }

  static const char* value(const ::integrated_navigation_reader::ASCIIHeader_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::integrated_navigation_reader::ASCIIHeader_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.port);
      stream.next(m.sequence);
      stream.next(m.idle_time);
      stream.next(m.time_status);
      stream.next(m.week);
      stream.next(m.seconds);
      stream.next(m.receiver_status);
      stream.next(m.reserved);
      stream.next(m.receiver_sw_version);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ASCIIHeader_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::integrated_navigation_reader::ASCIIHeader_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::integrated_navigation_reader::ASCIIHeader_<ContainerAllocator>& v)
  {
    s << indent << "port: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.port);
    s << indent << "sequence: ";
    Printer<int32_t>::stream(s, indent + "  ", v.sequence);
    s << indent << "idle_time: ";
    Printer<float>::stream(s, indent + "  ", v.idle_time);
    s << indent << "time_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.time_status);
    s << indent << "week: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.week);
    s << indent << "seconds: ";
    Printer<double>::stream(s, indent + "  ", v.seconds);
    s << indent << "receiver_status: ";
    s << std::endl;
    Printer< ::integrated_navigation_reader::Log_ReceiverStatus_<ContainerAllocator> >::stream(s, indent + "  ", v.receiver_status);
    s << indent << "reserved: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.reserved);
    s << indent << "receiver_sw_version: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.receiver_sw_version);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INTEGRATED_NAVIGATION_READER_MESSAGE_ASCIIHEADER_H
