// Generated by gencpp from file integrated_navigation_reader/SPANLog_INSPVAXA.msg
// DO NOT EDIT!


#ifndef INTEGRATED_NAVIGATION_READER_MESSAGE_SPANLOG_INSPVAXA_H
#define INTEGRATED_NAVIGATION_READER_MESSAGE_SPANLOG_INSPVAXA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <integrated_navigation_reader/ASCIIHeader.h>
#include <integrated_navigation_reader/SPANLog_INSStatus.h>
#include <integrated_navigation_reader/Log_PositionVelocityType.h>
#include <integrated_navigation_reader/SPANLog_ExtendedSolutionStatus.h>

namespace integrated_navigation_reader
{
template <class ContainerAllocator>
struct SPANLog_INSPVAXA_
{
  typedef SPANLog_INSPVAXA_<ContainerAllocator> Type;

  SPANLog_INSPVAXA_()
    : header()
    , log_header()
    , ins_status()
    , position_type()
    , latitude(0.0)
    , longitude(0.0)
    , height(0.0)
    , undulation(0.0)
    , north_velocity(0.0)
    , east_velocity(0.0)
    , up_velocity(0.0)
    , roll(0.0)
    , pitch(0.0)
    , azimuth(0.0)
    , latitude_std(0.0)
    , longitude_std(0.0)
    , height_std(0.0)
    , north_velocity_std(0.0)
    , east_velocity_std(0.0)
    , up_velocity_std(0.0)
    , roll_std(0.0)
    , pitch_std(0.0)
    , azimuth_std(0.0)
    , extended_solution_status()
    , time_since_update(0)  {
    }
  SPANLog_INSPVAXA_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , log_header(_alloc)
    , ins_status(_alloc)
    , position_type(_alloc)
    , latitude(0.0)
    , longitude(0.0)
    , height(0.0)
    , undulation(0.0)
    , north_velocity(0.0)
    , east_velocity(0.0)
    , up_velocity(0.0)
    , roll(0.0)
    , pitch(0.0)
    , azimuth(0.0)
    , latitude_std(0.0)
    , longitude_std(0.0)
    , height_std(0.0)
    , north_velocity_std(0.0)
    , east_velocity_std(0.0)
    , up_velocity_std(0.0)
    , roll_std(0.0)
    , pitch_std(0.0)
    , azimuth_std(0.0)
    , extended_solution_status(_alloc)
    , time_since_update(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::integrated_navigation_reader::ASCIIHeader_<ContainerAllocator>  _log_header_type;
  _log_header_type log_header;

   typedef  ::integrated_navigation_reader::SPANLog_INSStatus_<ContainerAllocator>  _ins_status_type;
  _ins_status_type ins_status;

   typedef  ::integrated_navigation_reader::Log_PositionVelocityType_<ContainerAllocator>  _position_type_type;
  _position_type_type position_type;

   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _height_type;
  _height_type height;

   typedef double _undulation_type;
  _undulation_type undulation;

   typedef double _north_velocity_type;
  _north_velocity_type north_velocity;

   typedef double _east_velocity_type;
  _east_velocity_type east_velocity;

   typedef double _up_velocity_type;
  _up_velocity_type up_velocity;

   typedef double _roll_type;
  _roll_type roll;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _azimuth_type;
  _azimuth_type azimuth;

   typedef double _latitude_std_type;
  _latitude_std_type latitude_std;

   typedef double _longitude_std_type;
  _longitude_std_type longitude_std;

   typedef double _height_std_type;
  _height_std_type height_std;

   typedef double _north_velocity_std_type;
  _north_velocity_std_type north_velocity_std;

   typedef double _east_velocity_std_type;
  _east_velocity_std_type east_velocity_std;

   typedef double _up_velocity_std_type;
  _up_velocity_std_type up_velocity_std;

   typedef double _roll_std_type;
  _roll_std_type roll_std;

   typedef double _pitch_std_type;
  _pitch_std_type pitch_std;

   typedef double _azimuth_std_type;
  _azimuth_std_type azimuth_std;

   typedef  ::integrated_navigation_reader::SPANLog_ExtendedSolutionStatus_<ContainerAllocator>  _extended_solution_status_type;
  _extended_solution_status_type extended_solution_status;

   typedef uint16_t _time_since_update_type;
  _time_since_update_type time_since_update;





  typedef boost::shared_ptr< ::integrated_navigation_reader::SPANLog_INSPVAXA_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::integrated_navigation_reader::SPANLog_INSPVAXA_<ContainerAllocator> const> ConstPtr;

}; // struct SPANLog_INSPVAXA_

typedef ::integrated_navigation_reader::SPANLog_INSPVAXA_<std::allocator<void> > SPANLog_INSPVAXA;

typedef boost::shared_ptr< ::integrated_navigation_reader::SPANLog_INSPVAXA > SPANLog_INSPVAXAPtr;
typedef boost::shared_ptr< ::integrated_navigation_reader::SPANLog_INSPVAXA const> SPANLog_INSPVAXAConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::integrated_navigation_reader::SPANLog_INSPVAXA_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::integrated_navigation_reader::SPANLog_INSPVAXA_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::integrated_navigation_reader::SPANLog_INSPVAXA_<ContainerAllocator1> & lhs, const ::integrated_navigation_reader::SPANLog_INSPVAXA_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.log_header == rhs.log_header &&
    lhs.ins_status == rhs.ins_status &&
    lhs.position_type == rhs.position_type &&
    lhs.latitude == rhs.latitude &&
    lhs.longitude == rhs.longitude &&
    lhs.height == rhs.height &&
    lhs.undulation == rhs.undulation &&
    lhs.north_velocity == rhs.north_velocity &&
    lhs.east_velocity == rhs.east_velocity &&
    lhs.up_velocity == rhs.up_velocity &&
    lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch &&
    lhs.azimuth == rhs.azimuth &&
    lhs.latitude_std == rhs.latitude_std &&
    lhs.longitude_std == rhs.longitude_std &&
    lhs.height_std == rhs.height_std &&
    lhs.north_velocity_std == rhs.north_velocity_std &&
    lhs.east_velocity_std == rhs.east_velocity_std &&
    lhs.up_velocity_std == rhs.up_velocity_std &&
    lhs.roll_std == rhs.roll_std &&
    lhs.pitch_std == rhs.pitch_std &&
    lhs.azimuth_std == rhs.azimuth_std &&
    lhs.extended_solution_status == rhs.extended_solution_status &&
    lhs.time_since_update == rhs.time_since_update;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::integrated_navigation_reader::SPANLog_INSPVAXA_<ContainerAllocator1> & lhs, const ::integrated_navigation_reader::SPANLog_INSPVAXA_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace integrated_navigation_reader

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::integrated_navigation_reader::SPANLog_INSPVAXA_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::integrated_navigation_reader::SPANLog_INSPVAXA_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::integrated_navigation_reader::SPANLog_INSPVAXA_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::integrated_navigation_reader::SPANLog_INSPVAXA_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::integrated_navigation_reader::SPANLog_INSPVAXA_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::integrated_navigation_reader::SPANLog_INSPVAXA_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::integrated_navigation_reader::SPANLog_INSPVAXA_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e8166f7934a2bb9f4df946a960c72bdd";
  }

  static const char* value(const ::integrated_navigation_reader::SPANLog_INSPVAXA_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe8166f7934a2bb9fULL;
  static const uint64_t static_value2 = 0x4df946a960c72bddULL;
};

template<class ContainerAllocator>
struct DataType< ::integrated_navigation_reader::SPANLog_INSPVAXA_<ContainerAllocator> >
{
  static const char* value()
  {
    return "integrated_navigation_reader/SPANLog_INSPVAXA";
  }

  static const char* value(const ::integrated_navigation_reader::SPANLog_INSPVAXA_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::integrated_navigation_reader::SPANLog_INSPVAXA_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# page 1082\n"
"std_msgs/Header header\n"
"\n"
"ASCIIHeader log_header\n"
"\n"
"# INS status\n"
"SPANLog_INSStatus ins_status\n"
"\n"
"#Position type\n"
"Log_PositionVelocityType position_type\n"
"\n"
"#Data\n"
"float64 latitude\n"
"float64 longitude\n"
"float64 height\n"
"float64 undulation\n"
"\n"
"float64 north_velocity\n"
"float64 east_velocity\n"
"float64 up_velocity\n"
"\n"
"float64 roll\n"
"float64 pitch\n"
"float64 azimuth\n"
"\n"
"float64 latitude_std\n"
"float64 longitude_std\n"
"float64 height_std\n"
"\n"
"float64 north_velocity_std\n"
"float64 east_velocity_std\n"
"float64 up_velocity_std\n"
"\n"
"float64 roll_std\n"
"float64 pitch_std\n"
"float64 azimuth_std\n"
"\n"
"#Extended solution status\n"
"SPANLog_ExtendedSolutionStatus extended_solution_status\n"
"\n"
"uint16 time_since_update\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: integrated_navigation_reader/ASCIIHeader\n"
"#INSPVAX header\n"
"\n"
"string port\n"
"int32 sequence\n"
"\n"
"float32 idle_time\n"
"\n"
"uint8 UNKNOWN = 20\n"
"uint8 APPROXIMATE = 60\n"
"uint8 COARSEADJUSTING = 80\n"
"uint8 COARSE = 100\n"
"uint8 COARSESTEERING = 120\n"
"uint8 FREEWHEELING = 130\n"
"uint8 FINEADJUSTING = 140\n"
"uint8 FINE = 160\n"
"uint8 FINEBACKUPSTEERING = 170\n"
"uint8 FINESTEERING = 180\n"
"uint8 SATTIME = 200\n"
"uint8 time_status\n"
"\n"
"uint32 week\n"
"float64 seconds\n"
"\n"
"Log_ReceiverStatus receiver_status\n"
"uint32 reserved\n"
"uint32 receiver_sw_version\n"
"================================================================================\n"
"MSG: integrated_navigation_reader/Log_ReceiverStatus\n"
"# Receiver status - page 858\n"
"\n"
"bool OK = 0\n"
"bool Valid = 0\n"
"bool No_error = 0\n"
"bool No_overrun = 0\n"
"\n"
"bool Warning = 1\n"
"bool Error = 1\n"
"bool Failure = 1\n"
"bool Overrun = 1\n"
"bool Invalid = 1\n"
"\n"
"# N0\n"
"bool error_flag\n"
"\n"
"bool Within_specifications = 0\n"
"bool temperature_status\n"
"bool voltage_supply_status\n"
"\n"
"bool Powered = 0\n"
"bool Not_powered = 1\n"
"bool primary_antenna_power_status\n"
"\n"
"# N1\n"
"bool LNA_failure\n"
"\n"
"bool Open_and_Antenna_disconnected = 1\n"
"bool primary_antenna_open_circuit_flag\n"
"\n"
"bool Short_circuit_detected = 1\n"
"bool primary_antenna_short_circuit_flag\n"
"\n"
"bool No_overload = 0\n"
"bool Overload = 1\n"
"bool CPU_overload_flag\n"
"\n"
"# N2\n"
"bool COM_port_transmit_buffer_overrun\n"
"\n"
"bool Not_detected = 0\n"
"bool Detected = 1\n"
"bool spoofing_detection_status\n"
"\n"
"bool reserved\n"
"bool link_overrun_flag\n"
"\n"
"# N3\n"
"bool input_overrun_flag\n"
"bool aux_transmit_overrun_flag\n"
"\n"
"bool Out_of_range = 1\n"
"bool antenna_gain_state\n"
"\n"
"bool Jammer_Detected = 1\n"
"bool jammer_detected\n"
"\n"
"# N4\n"
"bool No_INS_reset = 0\n"
"bool INS_reset = 1\n"
"bool INS_reset_flag\n"
"\n"
"bool No_IMU_communication = 1\n"
"bool IMU_communication_failure\n"
"\n"
"bool GPS_almanac_flag_UTC_known\n"
"bool position_solution_flag\n"
"\n"
"# N5\n"
"bool Not_fixed = 0\n"
"bool Fixed = 1\n"
"bool position_fixed_flag\n"
"\n"
"bool Enabled_clock_steering = 0\n"
"bool Disabled_clock_steering = 1\n"
"bool clock_steering_status\n"
"\n"
"bool clock_model_flag\n"
"\n"
"bool UnLocked = 0\n"
"bool Locked = 1\n"
"bool external_oscillator_locked_flag\n"
"\n"
"# N6\n"
"bool software_resource\n"
"\n"
"bool OEM6_or_earlier_format = 0\n"
"bool OEM7_format = 1\n"
"bool status_error_version_bit\n"
"\n"
"bool version_bit_1\n"
"\n"
"bool Normal_tracking = 0\n"
"bool HDR_tracking = 1\n"
"bool tracking_mode\n"
"\n"
"# N7\n"
"bool Disables_digital_filtering = 0\n"
"bool Enables_digital_filtering = 1\n"
"bool digital_filtering_enabled\n"
"\n"
"bool No_event = 0\n"
"bool Event = 1\n"
"bool auxiliary_3_status_event_flag\n"
"bool auxiliary_2_status_event_flag\n"
"bool auxiliary_1_status_event_flag\n"
"================================================================================\n"
"MSG: integrated_navigation_reader/SPANLog_INSStatus\n"
"# INS status - page 1055\n"
"\n"
"uint8 INS_INACTIVE = 0\n"
"uint8 INS_ALIGNING = 1\n"
"uint8 INS_HIGH_VARIANCE = 2\n"
"uint8 INS_SOLUTION_GOOD = 3\n"
"uint8 INS_SOLUTION_FREE = 6\n"
"uint8 INS_ALIGNMENT_COMPLETE = 7\n"
"uint8 DETERMINING_ORIENTATION = 8\n"
"uint8 WAITING_INITIALPOS = 9\n"
"uint8 WAITING_AZIMUTH = 10\n"
"uint8 INITIALIZING_BIASES = 11\n"
"uint8 MOTION_DETECT = 12\n"
"uint8 WAITING_ALIGNMENTORIENTATION = 14\n"
"uint8 status\n"
"================================================================================\n"
"MSG: integrated_navigation_reader/Log_PositionVelocityType\n"
"# Position type - page 501\n"
"\n"
"uint8 NONE = 0\n"
"uint8 FIXEDPOS = 1\n"
"uint8 FIXEDHEIGHT = 2\n"
"uint8 DOPPLER_VELOCITY = 8\n"
"uint8 SINGLE = 16\n"
"uint8 PSRDIFF = 17\n"
"uint8 WAAS = 18\n"
"uint8 PROPAGATED = 19\n"
"uint8 L1_FLOAT = 32\n"
"uint8 NARROW_FLOAT = 34\n"
"uint8 L1_INT = 48\n"
"uint8 WIDE_INT = 49\n"
"uint8 NARROW_INT = 50\n"
"uint8 RTK_DIRECT_INS = 51\n"
"uint8 INS_SBAS = 52\n"
"uint8 INS_PSRSP = 53\n"
"uint8 INS_PSRDIFF = 54\n"
"uint8 INS_RTKFLOAT = 55\n"
"uint8 INS_RTKFIXED = 56\n"
"uint8 PPP_CONVERGING = 68\n"
"uint8 PPP = 69\n"
"uint8 OPERATIONAL = 70\n"
"uint8 WARNING = 71\n"
"uint8 OUT_OF_BOUNDS = 72\n"
"uint8 INS_PPP_CONVERGING = 73\n"
"uint8 INS_PPP = 74\n"
"uint8 PPP_BASIC_CONVERGING = 77\n"
"uint8 PPP_BASIC = 78\n"
"uint8 INS_PPP_BASIC_CONVERGING = 79\n"
"uint8 INS_PPP_BASIC = 80\n"
"uint8 type\n"
"================================================================================\n"
"MSG: integrated_navigation_reader/SPANLog_ExtendedSolutionStatus\n"
"# Solution status - page 1060\n"
"\n"
"bool Unused = 0\n"
"bool Used = 1\n"
"\n"
"# N0\n"
"bool position_update\n"
"bool phase_update\n"
"bool zero_velocity_update\n"
"bool wheel_sensor_update\n"
"\n"
"# N1\n"
"bool ALIGN_heading_update\n"
"bool external_position_update\n"
"\n"
"bool Not_converged = 0\n"
"bool Converged = 1\n"
"bool INS_solution_convergence_flag\n"
"\n"
"bool doppler_update\n"
"\n"
"# N2\n"
"bool pseudorange_update\n"
"bool velocity_update\n"
"bool reserved_bit_10\n"
"bool dead_reckoning_update\n"
"\n"
"# N3\n"
"bool phase_wind_up_update\n"
"bool course_over_ground_update\n"
"bool external_velocity_update\n"
"bool external_attitude_update\n"
"\n"
"# N4\n"
"bool external_heading_update\n"
"bool external_height_update\n"
"bool reserved_bit_18\n"
"bool reserved_bit_19\n"
"\n"
"# N5\n"
"bool reserved_bit_20\n"
"bool reserved_bit_21\n"
"\n"
"bool secondary_INS_solution\n"
"bool reserved_bit_23\n"
"\n"
"# N6-7\n"
"bool Biases_not_estimated = 0\n"
"bool Biases_estimated = 1\n"
"bool turn_on_biases_estimated\n"
"\n"
"bool Not_verified = 0\n"
"bool Verified = 1\n"
"bool alignment_direction_verified\n"
"\n"
"uint8 Incomplete_Alignment = 0\n"
"uint8 Static = 1\n"
"uint8 Kinematic = 2\n"
"uint8 Dual_Antenna = 3\n"
"uint8 User_Command = 4\n"
"uint8 NVM_Seed = 5\n"
"uint8 alignment_indication\n"
"\n"
"uint8 Not_Injected = 0\n"
"uint8 Valid_Not_Found = 1\n"
"uint8 Failed_Validation_and_Discarded = 2\n"
"uint8 Awaiting_Validation = 3\n"
"uint8 Alignment_Data_Injected = 4\n"
"uint8 Ignored = 5\n"
"uint8 Error_Model_Data_Injected = 6\n"
"uint8 NVM_seed_indication\n"
;
  }

  static const char* value(const ::integrated_navigation_reader::SPANLog_INSPVAXA_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::integrated_navigation_reader::SPANLog_INSPVAXA_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.log_header);
      stream.next(m.ins_status);
      stream.next(m.position_type);
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.height);
      stream.next(m.undulation);
      stream.next(m.north_velocity);
      stream.next(m.east_velocity);
      stream.next(m.up_velocity);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.azimuth);
      stream.next(m.latitude_std);
      stream.next(m.longitude_std);
      stream.next(m.height_std);
      stream.next(m.north_velocity_std);
      stream.next(m.east_velocity_std);
      stream.next(m.up_velocity_std);
      stream.next(m.roll_std);
      stream.next(m.pitch_std);
      stream.next(m.azimuth_std);
      stream.next(m.extended_solution_status);
      stream.next(m.time_since_update);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SPANLog_INSPVAXA_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::integrated_navigation_reader::SPANLog_INSPVAXA_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::integrated_navigation_reader::SPANLog_INSPVAXA_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "log_header: ";
    s << std::endl;
    Printer< ::integrated_navigation_reader::ASCIIHeader_<ContainerAllocator> >::stream(s, indent + "  ", v.log_header);
    s << indent << "ins_status: ";
    s << std::endl;
    Printer< ::integrated_navigation_reader::SPANLog_INSStatus_<ContainerAllocator> >::stream(s, indent + "  ", v.ins_status);
    s << indent << "position_type: ";
    s << std::endl;
    Printer< ::integrated_navigation_reader::Log_PositionVelocityType_<ContainerAllocator> >::stream(s, indent + "  ", v.position_type);
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "height: ";
    Printer<double>::stream(s, indent + "  ", v.height);
    s << indent << "undulation: ";
    Printer<double>::stream(s, indent + "  ", v.undulation);
    s << indent << "north_velocity: ";
    Printer<double>::stream(s, indent + "  ", v.north_velocity);
    s << indent << "east_velocity: ";
    Printer<double>::stream(s, indent + "  ", v.east_velocity);
    s << indent << "up_velocity: ";
    Printer<double>::stream(s, indent + "  ", v.up_velocity);
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "azimuth: ";
    Printer<double>::stream(s, indent + "  ", v.azimuth);
    s << indent << "latitude_std: ";
    Printer<double>::stream(s, indent + "  ", v.latitude_std);
    s << indent << "longitude_std: ";
    Printer<double>::stream(s, indent + "  ", v.longitude_std);
    s << indent << "height_std: ";
    Printer<double>::stream(s, indent + "  ", v.height_std);
    s << indent << "north_velocity_std: ";
    Printer<double>::stream(s, indent + "  ", v.north_velocity_std);
    s << indent << "east_velocity_std: ";
    Printer<double>::stream(s, indent + "  ", v.east_velocity_std);
    s << indent << "up_velocity_std: ";
    Printer<double>::stream(s, indent + "  ", v.up_velocity_std);
    s << indent << "roll_std: ";
    Printer<double>::stream(s, indent + "  ", v.roll_std);
    s << indent << "pitch_std: ";
    Printer<double>::stream(s, indent + "  ", v.pitch_std);
    s << indent << "azimuth_std: ";
    Printer<double>::stream(s, indent + "  ", v.azimuth_std);
    s << indent << "extended_solution_status: ";
    s << std::endl;
    Printer< ::integrated_navigation_reader::SPANLog_ExtendedSolutionStatus_<ContainerAllocator> >::stream(s, indent + "  ", v.extended_solution_status);
    s << indent << "time_since_update: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.time_since_update);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INTEGRATED_NAVIGATION_READER_MESSAGE_SPANLOG_INSPVAXA_H
